version: '3'

services: 
    flaskapp:
        build: ./flaskapp-docker
        #container_name: flaskapp
        #network_mode: host
        environment: 
            - AWS_PROFILE=csloginstudent
            - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
            - AWS_CONFIG_FILE=/aws/config
    nginx:
        build: ./data/nginx
        container_name: nginx
        environment: 
        #    - SERVER_NAME=52.22.32.81
             - SERVER_NAME=filrouge.pbo.p2021.ajoga.fr
        restart: always
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - flaskapp
        #network_mode: host
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
  
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

