version: '3'

services: 
    flaskapp:
        build: ./flaskapp-docker
        container_name: flaskapp
        network_mode: host
        environment: 
            - AWS_PROFILE=csloginstudent
            - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
            - AWS_CONFIG_FILE=/aws/config
    nginx:
        build: ./nginx
        container_name: nginx
        environment: 
            - SERVER_NAME=54.146.138.136
        restart: always
        network_mode: host
